{% set version = "1.21.3" %}

package:
  name: wget
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/wget/wget-{{ version }}.tar.gz
  sha256: 5726bb8bc5ca0f6dc7110f6416e4bb7019e2d2ff5bf93d1ca2ffcc6656f220e5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - openssl
    - libidn2
    - libunistring
    - zlib
  run:
    - openssl
    - libidn2
    - libunistring
    - zlib

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget/
  doc_source_url: https://savannah.gnu.org/projects/wget/

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.
