{% set version = "1.20.2" %}

package:
  name: wget
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/wget/wget-{{ version }}.tar.gz
  sha256: 7e43b98cb5e10234836ebef6faf24c4d96c0ae7a480e49ff658117cc4793d166

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - openssl
    - libidn2
    - libunistring
    - zlib
  run:
    - openssl
    - libidn2
    - libunistring
    - zlib

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget/
  license: GPL3
  license_file: COPYING
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget/
  doc_source_url: https://savannah.gnu.org/projects/wget/

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.
